name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: j18e/elvanto-overview
        registry: docker.io
        username: j18e
        password: ${{ secrets.DOCKER_PASSWORD }}
        addLatest: true
        addTimestamp: false
